module.exports = {
  Achievement: require('./achievement')
  Achievement_Category: require('./achievement-category')
  Achievement_Criteria: require('./achievement-criteria')
  AnimationData: require('./animation-data')
  AreaGroup: require('./area-group')
  AreaPOI: require('./area-poi')
  AreaTable: require('./area-table')
  AreaTrigger: require('./area-trigger')
  ChrClasses: require('./chr-classes')
  ChrRaces: require('./chr-races')
  CreatureDisplayInfo: require('./creature-display-info')
  CreatureModelData: require('./creature-model-data')
  Faction: require('./faction')
  Map: require('./map')
}
