import r from 'restructure';

import Entity from '../entity';

export default Entity({
  ID: r.int32le,
  Flags: r.int32le,
  AttachmentID: r.int32le,
  AttachmentOffsetX: r.floatle,
  AttachmentOffsetY: r.floatle,
  AttachmentOffsetZ: r.floatle,
  EnterPreDelay: r.floatle,
  EnterSpeed: r.floatle,
  EnterGravity: r.floatle,
  EnterMinDuration: r.floatle,
  EnterMaxDuration: r.floatle,
  EnterMinArcHeight: r.floatle,
  EnterMaxArcHeight: r.floatle,
  EnterAnimStart: r.int32le,
  EnterAnimLoop: r.int32le,
  RideAnimStart: r.int32le,
  RideAnimLoop: r.int32le,
  RideUpperAnimStart: r.int32le,
  RideUpperAnimLoop: r.int32le,
  ExitPreDelay: r.floatle,
  ExitSpeed: r.floatle,
  ExitGravity: r.floatle,
  ExitMinDuration: r.floatle,
  ExitMaxDuration: r.floatle,
  ExitMinArcHeight: r.floatle,
  ExitMaxArcHeight: r.floatle,
  ExitAnimStart: r.int32le,
  ExitAnimLoop: r.int32le,
  ExitAnimEnd: r.int32le,
  PassengerYaw: r.floatle,
  PassengerPitch: r.floatle,
  PassengerRoll: r.floatle,
  PassengerAttachmentID: r.int32le,
  VehicleEnterAnim: r.int32le,
  VehicleExitAnim: r.int32le,
  VehicleRideAnimLoop: r.int32le,
  VehicleEnterAnimBone: r.int32le,
  VehicleExitAnimBone: r.int32le,
  VehicleRideAnimLoopBone: r.int32le,
  VehicleEnterAnimDelay: r.floatle,
  VehicleExitAnimDelay: r.floatle,
  VehicleAbilityDisplay: r.int32le,
  EnterUISoundID: r.int32le,
  ExitUISoundID: r.int32le,
  UiSkin: r.int32le,
  FlagsB: r.int32le,
  CameraEnteringDelay: r.floatle,
  CameraEnteringDuration: r.floatle,
  CameraExitingDelay: r.floatle,
  CameraExitingDuration: r.floatle,
  CameraOffsetX: r.floatle,
  CameraOffsetY: r.floatle,
  CameraOffsetZ: r.floatle,
  CameraPosChaseRate: r.floatle,
  CameraFacingChaseRate: r.floatle,
  CameraEnteringZoom: r.floatle,
  CameraSeatZoomMin: r.floatle,
  CameraSeatZoomMax: r.floatle,
});
