module.exports = {
  Achievement: require('./achievement'),
  Achievement_Category: require('./achievement-category'),
  Achievement_Criteria: require('./achievement-criteria'),
  AnimationData: require('./animation-data'),
  AreaGroup: require('./area-group'),
  AreaPOI: require('./area-poi'),
  AreaTable: require('./area-table'),
  AreaTrigger: require('./area-trigger'),
  AttackAnimKits: require('./attack-anim-kits'),
  AttackAnimTypes: require('./attack-anim-types'),
  AuctionHouse: require('./auction-house'),
  BankBagSlotPrices: require('./bank-bag-slot-prices'),
  BannedAddOns: require('./banned-add-ons'),
  BarberShopStyle: require('./barber-shop-style'),
  BattlemasterList: require('./battlemaster-list'),
  CameraShakes: require('./camera-shakes'),
  Cfg_Categories: require('./cfg-categories'),
  ChrClasses: require('./chr-classes'),
  ChrRaces: require('./chr-races'),
  CreatureDisplayInfo: require('./creature-display-info'),
  CreatureModelData: require('./creature-model-data'),
  Faction: require('./faction'),
  Map: require('./map')
};
